version: "3.8"
services:
  app:
    build: .
    env_file:
      - .env
    container_name: media-share-backend
    ports:
      - "3005:3000"
    environment:
      MONGO_URL: mongodb://database:27017/mediaShare2
    depends_on:
      - database
    networks:
      - dam
   

  database:
    image: mongo:6
    container_name: mongo_MediaShare
    ports:
      - "3006:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - dam

volumes:
  mongo-data:
networks:
  dam: